# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panpan/workspace/despot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panpan/workspace/despot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panpan/workspace/despot/CMakeFiles /home/panpan/workspace/despot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panpan/workspace/despot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named despot

# Build rule for target.
despot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot
.PHONY : despot

# fast build rule for target.
despot/fast:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/build
.PHONY : despot/fast

#=============================================================================
# Target rules for targets named despot_adventurer

# Build rule for target.
despot_adventurer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_adventurer
.PHONY : despot_adventurer

# fast build rule for target.
despot_adventurer/fast:
	$(MAKE) -f examples/cpp_models/adventurer/CMakeFiles/despot_adventurer.dir/build.make examples/cpp_models/adventurer/CMakeFiles/despot_adventurer.dir/build
.PHONY : despot_adventurer/fast

#=============================================================================
# Target rules for targets named despot_bridge

# Build rule for target.
despot_bridge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_bridge
.PHONY : despot_bridge

# fast build rule for target.
despot_bridge/fast:
	$(MAKE) -f examples/cpp_models/bridge/CMakeFiles/despot_bridge.dir/build.make examples/cpp_models/bridge/CMakeFiles/despot_bridge.dir/build
.PHONY : despot_bridge/fast

#=============================================================================
# Target rules for targets named despot_chain

# Build rule for target.
despot_chain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_chain
.PHONY : despot_chain

# fast build rule for target.
despot_chain/fast:
	$(MAKE) -f examples/cpp_models/chain/CMakeFiles/despot_chain.dir/build.make examples/cpp_models/chain/CMakeFiles/despot_chain.dir/build
.PHONY : despot_chain/fast

#=============================================================================
# Target rules for targets named despot_navigation

# Build rule for target.
despot_navigation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_navigation
.PHONY : despot_navigation

# fast build rule for target.
despot_navigation/fast:
	$(MAKE) -f examples/cpp_models/navigation/CMakeFiles/despot_navigation.dir/build.make examples/cpp_models/navigation/CMakeFiles/despot_navigation.dir/build
.PHONY : despot_navigation/fast

#=============================================================================
# Target rules for targets named despot_pocman

# Build rule for target.
despot_pocman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_pocman
.PHONY : despot_pocman

# fast build rule for target.
despot_pocman/fast:
	$(MAKE) -f examples/cpp_models/pocman/CMakeFiles/despot_pocman.dir/build.make examples/cpp_models/pocman/CMakeFiles/despot_pocman.dir/build
.PHONY : despot_pocman/fast

#=============================================================================
# Target rules for targets named despot_reg_demo

# Build rule for target.
despot_reg_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_reg_demo
.PHONY : despot_reg_demo

# fast build rule for target.
despot_reg_demo/fast:
	$(MAKE) -f examples/cpp_models/reg_demo/CMakeFiles/despot_reg_demo.dir/build.make examples/cpp_models/reg_demo/CMakeFiles/despot_reg_demo.dir/build
.PHONY : despot_reg_demo/fast

#=============================================================================
# Target rules for targets named despot_fvrs

# Build rule for target.
despot_fvrs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_fvrs
.PHONY : despot_fvrs

# fast build rule for target.
despot_fvrs/fast:
	$(MAKE) -f examples/cpp_models/rock_sample/CMakeFiles/despot_fvrs.dir/build.make examples/cpp_models/rock_sample/CMakeFiles/despot_fvrs.dir/build
.PHONY : despot_fvrs/fast

#=============================================================================
# Target rules for targets named despot_rock_sample

# Build rule for target.
despot_rock_sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_rock_sample
.PHONY : despot_rock_sample

# fast build rule for target.
despot_rock_sample/fast:
	$(MAKE) -f examples/cpp_models/rock_sample/CMakeFiles/despot_rock_sample.dir/build.make examples/cpp_models/rock_sample/CMakeFiles/despot_rock_sample.dir/build
.PHONY : despot_rock_sample/fast

#=============================================================================
# Target rules for targets named despot_simple_rock_sample

# Build rule for target.
despot_simple_rock_sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_simple_rock_sample
.PHONY : despot_simple_rock_sample

# fast build rule for target.
despot_simple_rock_sample/fast:
	$(MAKE) -f examples/cpp_models/simple_rock_sample/CMakeFiles/despot_simple_rock_sample.dir/build.make examples/cpp_models/simple_rock_sample/CMakeFiles/despot_simple_rock_sample.dir/build
.PHONY : despot_simple_rock_sample/fast

#=============================================================================
# Target rules for targets named despot_tag

# Build rule for target.
despot_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_tag
.PHONY : despot_tag

# fast build rule for target.
despot_tag/fast:
	$(MAKE) -f examples/cpp_models/tag/CMakeFiles/despot_tag.dir/build.make examples/cpp_models/tag/CMakeFiles/despot_tag.dir/build
.PHONY : despot_tag/fast

#=============================================================================
# Target rules for targets named despot_noisy_laser_tag

# Build rule for target.
despot_noisy_laser_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_noisy_laser_tag
.PHONY : despot_noisy_laser_tag

# fast build rule for target.
despot_noisy_laser_tag/fast:
	$(MAKE) -f examples/cpp_models/tag/CMakeFiles/despot_noisy_laser_tag.dir/build.make examples/cpp_models/tag/CMakeFiles/despot_noisy_laser_tag.dir/build
.PHONY : despot_noisy_laser_tag/fast

#=============================================================================
# Target rules for targets named despot_laser_tag

# Build rule for target.
despot_laser_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_laser_tag
.PHONY : despot_laser_tag

# fast build rule for target.
despot_laser_tag/fast:
	$(MAKE) -f examples/cpp_models/tag/CMakeFiles/despot_laser_tag.dir/build.make examples/cpp_models/tag/CMakeFiles/despot_laser_tag.dir/build
.PHONY : despot_laser_tag/fast

#=============================================================================
# Target rules for targets named despot_tiger

# Build rule for target.
despot_tiger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_tiger
.PHONY : despot_tiger

# fast build rule for target.
despot_tiger/fast:
	$(MAKE) -f examples/cpp_models/tiger/CMakeFiles/despot_tiger.dir/build.make examples/cpp_models/tiger/CMakeFiles/despot_tiger.dir/build
.PHONY : despot_tiger/fast

#=============================================================================
# Target rules for targets named despot_pomdpx

# Build rule for target.
despot_pomdpx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 despot_pomdpx
.PHONY : despot_pomdpx

# fast build rule for target.
despot_pomdpx/fast:
	$(MAKE) -f examples/pomdpx_models/CMakeFiles/despot_pomdpx.dir/build.make examples/pomdpx_models/CMakeFiles/despot_pomdpx.dir/build
.PHONY : despot_pomdpx/fast

src/core/builtin_lower_bounds.o: src/core/builtin_lower_bounds.cpp.o

.PHONY : src/core/builtin_lower_bounds.o

# target to build an object file
src/core/builtin_lower_bounds.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_lower_bounds.cpp.o
.PHONY : src/core/builtin_lower_bounds.cpp.o

src/core/builtin_lower_bounds.i: src/core/builtin_lower_bounds.cpp.i

.PHONY : src/core/builtin_lower_bounds.i

# target to preprocess a source file
src/core/builtin_lower_bounds.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_lower_bounds.cpp.i
.PHONY : src/core/builtin_lower_bounds.cpp.i

src/core/builtin_lower_bounds.s: src/core/builtin_lower_bounds.cpp.s

.PHONY : src/core/builtin_lower_bounds.s

# target to generate assembly for a file
src/core/builtin_lower_bounds.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_lower_bounds.cpp.s
.PHONY : src/core/builtin_lower_bounds.cpp.s

src/core/builtin_policy.o: src/core/builtin_policy.cpp.o

.PHONY : src/core/builtin_policy.o

# target to build an object file
src/core/builtin_policy.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_policy.cpp.o
.PHONY : src/core/builtin_policy.cpp.o

src/core/builtin_policy.i: src/core/builtin_policy.cpp.i

.PHONY : src/core/builtin_policy.i

# target to preprocess a source file
src/core/builtin_policy.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_policy.cpp.i
.PHONY : src/core/builtin_policy.cpp.i

src/core/builtin_policy.s: src/core/builtin_policy.cpp.s

.PHONY : src/core/builtin_policy.s

# target to generate assembly for a file
src/core/builtin_policy.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_policy.cpp.s
.PHONY : src/core/builtin_policy.cpp.s

src/core/builtin_upper_bounds.o: src/core/builtin_upper_bounds.cpp.o

.PHONY : src/core/builtin_upper_bounds.o

# target to build an object file
src/core/builtin_upper_bounds.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_upper_bounds.cpp.o
.PHONY : src/core/builtin_upper_bounds.cpp.o

src/core/builtin_upper_bounds.i: src/core/builtin_upper_bounds.cpp.i

.PHONY : src/core/builtin_upper_bounds.i

# target to preprocess a source file
src/core/builtin_upper_bounds.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_upper_bounds.cpp.i
.PHONY : src/core/builtin_upper_bounds.cpp.i

src/core/builtin_upper_bounds.s: src/core/builtin_upper_bounds.cpp.s

.PHONY : src/core/builtin_upper_bounds.s

# target to generate assembly for a file
src/core/builtin_upper_bounds.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/builtin_upper_bounds.cpp.s
.PHONY : src/core/builtin_upper_bounds.cpp.s

src/core/globals.o: src/core/globals.cpp.o

.PHONY : src/core/globals.o

# target to build an object file
src/core/globals.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/globals.cpp.o
.PHONY : src/core/globals.cpp.o

src/core/globals.i: src/core/globals.cpp.i

.PHONY : src/core/globals.i

# target to preprocess a source file
src/core/globals.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/globals.cpp.i
.PHONY : src/core/globals.cpp.i

src/core/globals.s: src/core/globals.cpp.s

.PHONY : src/core/globals.s

# target to generate assembly for a file
src/core/globals.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/globals.cpp.s
.PHONY : src/core/globals.cpp.s

src/core/mdp.o: src/core/mdp.cpp.o

.PHONY : src/core/mdp.o

# target to build an object file
src/core/mdp.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/mdp.cpp.o
.PHONY : src/core/mdp.cpp.o

src/core/mdp.i: src/core/mdp.cpp.i

.PHONY : src/core/mdp.i

# target to preprocess a source file
src/core/mdp.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/mdp.cpp.i
.PHONY : src/core/mdp.cpp.i

src/core/mdp.s: src/core/mdp.cpp.s

.PHONY : src/core/mdp.s

# target to generate assembly for a file
src/core/mdp.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/mdp.cpp.s
.PHONY : src/core/mdp.cpp.s

src/core/node.o: src/core/node.cpp.o

.PHONY : src/core/node.o

# target to build an object file
src/core/node.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/node.cpp.o
.PHONY : src/core/node.cpp.o

src/core/node.i: src/core/node.cpp.i

.PHONY : src/core/node.i

# target to preprocess a source file
src/core/node.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/node.cpp.i
.PHONY : src/core/node.cpp.i

src/core/node.s: src/core/node.cpp.s

.PHONY : src/core/node.s

# target to generate assembly for a file
src/core/node.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/node.cpp.s
.PHONY : src/core/node.cpp.s

src/core/particle_belief.o: src/core/particle_belief.cpp.o

.PHONY : src/core/particle_belief.o

# target to build an object file
src/core/particle_belief.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/particle_belief.cpp.o
.PHONY : src/core/particle_belief.cpp.o

src/core/particle_belief.i: src/core/particle_belief.cpp.i

.PHONY : src/core/particle_belief.i

# target to preprocess a source file
src/core/particle_belief.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/particle_belief.cpp.i
.PHONY : src/core/particle_belief.cpp.i

src/core/particle_belief.s: src/core/particle_belief.cpp.s

.PHONY : src/core/particle_belief.s

# target to generate assembly for a file
src/core/particle_belief.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/particle_belief.cpp.s
.PHONY : src/core/particle_belief.cpp.s

src/core/pomdp_world.o: src/core/pomdp_world.cpp.o

.PHONY : src/core/pomdp_world.o

# target to build an object file
src/core/pomdp_world.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/pomdp_world.cpp.o
.PHONY : src/core/pomdp_world.cpp.o

src/core/pomdp_world.i: src/core/pomdp_world.cpp.i

.PHONY : src/core/pomdp_world.i

# target to preprocess a source file
src/core/pomdp_world.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/pomdp_world.cpp.i
.PHONY : src/core/pomdp_world.cpp.i

src/core/pomdp_world.s: src/core/pomdp_world.cpp.s

.PHONY : src/core/pomdp_world.s

# target to generate assembly for a file
src/core/pomdp_world.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/pomdp_world.cpp.s
.PHONY : src/core/pomdp_world.cpp.s

src/core/solver.o: src/core/solver.cpp.o

.PHONY : src/core/solver.o

# target to build an object file
src/core/solver.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/solver.cpp.o
.PHONY : src/core/solver.cpp.o

src/core/solver.i: src/core/solver.cpp.i

.PHONY : src/core/solver.i

# target to preprocess a source file
src/core/solver.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/solver.cpp.i
.PHONY : src/core/solver.cpp.i

src/core/solver.s: src/core/solver.cpp.s

.PHONY : src/core/solver.s

# target to generate assembly for a file
src/core/solver.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/core/solver.cpp.s
.PHONY : src/core/solver.cpp.s

src/evaluator.o: src/evaluator.cpp.o

.PHONY : src/evaluator.o

# target to build an object file
src/evaluator.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/evaluator.cpp.o
.PHONY : src/evaluator.cpp.o

src/evaluator.i: src/evaluator.cpp.i

.PHONY : src/evaluator.i

# target to preprocess a source file
src/evaluator.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/evaluator.cpp.i
.PHONY : src/evaluator.cpp.i

src/evaluator.s: src/evaluator.cpp.s

.PHONY : src/evaluator.s

# target to generate assembly for a file
src/evaluator.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/evaluator.cpp.s
.PHONY : src/evaluator.cpp.s

src/interface/belief.o: src/interface/belief.cpp.o

.PHONY : src/interface/belief.o

# target to build an object file
src/interface/belief.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/belief.cpp.o
.PHONY : src/interface/belief.cpp.o

src/interface/belief.i: src/interface/belief.cpp.i

.PHONY : src/interface/belief.i

# target to preprocess a source file
src/interface/belief.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/belief.cpp.i
.PHONY : src/interface/belief.cpp.i

src/interface/belief.s: src/interface/belief.cpp.s

.PHONY : src/interface/belief.s

# target to generate assembly for a file
src/interface/belief.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/belief.cpp.s
.PHONY : src/interface/belief.cpp.s

src/interface/default_policy.o: src/interface/default_policy.cpp.o

.PHONY : src/interface/default_policy.o

# target to build an object file
src/interface/default_policy.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/default_policy.cpp.o
.PHONY : src/interface/default_policy.cpp.o

src/interface/default_policy.i: src/interface/default_policy.cpp.i

.PHONY : src/interface/default_policy.i

# target to preprocess a source file
src/interface/default_policy.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/default_policy.cpp.i
.PHONY : src/interface/default_policy.cpp.i

src/interface/default_policy.s: src/interface/default_policy.cpp.s

.PHONY : src/interface/default_policy.s

# target to generate assembly for a file
src/interface/default_policy.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/default_policy.cpp.s
.PHONY : src/interface/default_policy.cpp.s

src/interface/lower_bound.o: src/interface/lower_bound.cpp.o

.PHONY : src/interface/lower_bound.o

# target to build an object file
src/interface/lower_bound.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/lower_bound.cpp.o
.PHONY : src/interface/lower_bound.cpp.o

src/interface/lower_bound.i: src/interface/lower_bound.cpp.i

.PHONY : src/interface/lower_bound.i

# target to preprocess a source file
src/interface/lower_bound.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/lower_bound.cpp.i
.PHONY : src/interface/lower_bound.cpp.i

src/interface/lower_bound.s: src/interface/lower_bound.cpp.s

.PHONY : src/interface/lower_bound.s

# target to generate assembly for a file
src/interface/lower_bound.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/lower_bound.cpp.s
.PHONY : src/interface/lower_bound.cpp.s

src/interface/pomdp.o: src/interface/pomdp.cpp.o

.PHONY : src/interface/pomdp.o

# target to build an object file
src/interface/pomdp.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/pomdp.cpp.o
.PHONY : src/interface/pomdp.cpp.o

src/interface/pomdp.i: src/interface/pomdp.cpp.i

.PHONY : src/interface/pomdp.i

# target to preprocess a source file
src/interface/pomdp.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/pomdp.cpp.i
.PHONY : src/interface/pomdp.cpp.i

src/interface/pomdp.s: src/interface/pomdp.cpp.s

.PHONY : src/interface/pomdp.s

# target to generate assembly for a file
src/interface/pomdp.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/pomdp.cpp.s
.PHONY : src/interface/pomdp.cpp.s

src/interface/upper_bound.o: src/interface/upper_bound.cpp.o

.PHONY : src/interface/upper_bound.o

# target to build an object file
src/interface/upper_bound.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/upper_bound.cpp.o
.PHONY : src/interface/upper_bound.cpp.o

src/interface/upper_bound.i: src/interface/upper_bound.cpp.i

.PHONY : src/interface/upper_bound.i

# target to preprocess a source file
src/interface/upper_bound.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/upper_bound.cpp.i
.PHONY : src/interface/upper_bound.cpp.i

src/interface/upper_bound.s: src/interface/upper_bound.cpp.s

.PHONY : src/interface/upper_bound.s

# target to generate assembly for a file
src/interface/upper_bound.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/upper_bound.cpp.s
.PHONY : src/interface/upper_bound.cpp.s

src/interface/world.o: src/interface/world.cpp.o

.PHONY : src/interface/world.o

# target to build an object file
src/interface/world.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/world.cpp.o
.PHONY : src/interface/world.cpp.o

src/interface/world.i: src/interface/world.cpp.i

.PHONY : src/interface/world.i

# target to preprocess a source file
src/interface/world.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/world.cpp.i
.PHONY : src/interface/world.cpp.i

src/interface/world.s: src/interface/world.cpp.s

.PHONY : src/interface/world.s

# target to generate assembly for a file
src/interface/world.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/interface/world.cpp.s
.PHONY : src/interface/world.cpp.s

src/logger.o: src/logger.cpp.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/planner.o: src/planner.cpp.o

.PHONY : src/planner.o

# target to build an object file
src/planner.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/planner.cpp.o
.PHONY : src/planner.cpp.o

src/planner.i: src/planner.cpp.i

.PHONY : src/planner.i

# target to preprocess a source file
src/planner.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/planner.cpp.i
.PHONY : src/planner.cpp.i

src/planner.s: src/planner.cpp.s

.PHONY : src/planner.s

# target to generate assembly for a file
src/planner.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/planner.cpp.s
.PHONY : src/planner.cpp.s

src/plannerbase.o: src/plannerbase.cpp.o

.PHONY : src/plannerbase.o

# target to build an object file
src/plannerbase.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/plannerbase.cpp.o
.PHONY : src/plannerbase.cpp.o

src/plannerbase.i: src/plannerbase.cpp.i

.PHONY : src/plannerbase.i

# target to preprocess a source file
src/plannerbase.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/plannerbase.cpp.i
.PHONY : src/plannerbase.cpp.i

src/plannerbase.s: src/plannerbase.cpp.s

.PHONY : src/plannerbase.s

# target to generate assembly for a file
src/plannerbase.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/plannerbase.cpp.s
.PHONY : src/plannerbase.cpp.s

src/pomdpx/parser/function.o: src/pomdpx/parser/function.cpp.o

.PHONY : src/pomdpx/parser/function.o

# target to build an object file
src/pomdpx/parser/function.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/function.cpp.o
.PHONY : src/pomdpx/parser/function.cpp.o

src/pomdpx/parser/function.i: src/pomdpx/parser/function.cpp.i

.PHONY : src/pomdpx/parser/function.i

# target to preprocess a source file
src/pomdpx/parser/function.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/function.cpp.i
.PHONY : src/pomdpx/parser/function.cpp.i

src/pomdpx/parser/function.s: src/pomdpx/parser/function.cpp.s

.PHONY : src/pomdpx/parser/function.s

# target to generate assembly for a file
src/pomdpx/parser/function.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/function.cpp.s
.PHONY : src/pomdpx/parser/function.cpp.s

src/pomdpx/parser/parser.o: src/pomdpx/parser/parser.cpp.o

.PHONY : src/pomdpx/parser/parser.o

# target to build an object file
src/pomdpx/parser/parser.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/parser.cpp.o
.PHONY : src/pomdpx/parser/parser.cpp.o

src/pomdpx/parser/parser.i: src/pomdpx/parser/parser.cpp.i

.PHONY : src/pomdpx/parser/parser.i

# target to preprocess a source file
src/pomdpx/parser/parser.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/parser.cpp.i
.PHONY : src/pomdpx/parser/parser.cpp.i

src/pomdpx/parser/parser.s: src/pomdpx/parser/parser.cpp.s

.PHONY : src/pomdpx/parser/parser.s

# target to generate assembly for a file
src/pomdpx/parser/parser.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/parser.cpp.s
.PHONY : src/pomdpx/parser/parser.cpp.s

src/pomdpx/parser/variable.o: src/pomdpx/parser/variable.cpp.o

.PHONY : src/pomdpx/parser/variable.o

# target to build an object file
src/pomdpx/parser/variable.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/variable.cpp.o
.PHONY : src/pomdpx/parser/variable.cpp.o

src/pomdpx/parser/variable.i: src/pomdpx/parser/variable.cpp.i

.PHONY : src/pomdpx/parser/variable.i

# target to preprocess a source file
src/pomdpx/parser/variable.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/variable.cpp.i
.PHONY : src/pomdpx/parser/variable.cpp.i

src/pomdpx/parser/variable.s: src/pomdpx/parser/variable.cpp.s

.PHONY : src/pomdpx/parser/variable.s

# target to generate assembly for a file
src/pomdpx/parser/variable.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/parser/variable.cpp.s
.PHONY : src/pomdpx/parser/variable.cpp.s

src/pomdpx/pomdpx.o: src/pomdpx/pomdpx.cpp.o

.PHONY : src/pomdpx/pomdpx.o

# target to build an object file
src/pomdpx/pomdpx.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/pomdpx.cpp.o
.PHONY : src/pomdpx/pomdpx.cpp.o

src/pomdpx/pomdpx.i: src/pomdpx/pomdpx.cpp.i

.PHONY : src/pomdpx/pomdpx.i

# target to preprocess a source file
src/pomdpx/pomdpx.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/pomdpx.cpp.i
.PHONY : src/pomdpx/pomdpx.cpp.i

src/pomdpx/pomdpx.s: src/pomdpx/pomdpx.cpp.s

.PHONY : src/pomdpx/pomdpx.s

# target to generate assembly for a file
src/pomdpx/pomdpx.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/pomdpx/pomdpx.cpp.s
.PHONY : src/pomdpx/pomdpx.cpp.s

src/random_streams.o: src/random_streams.cpp.o

.PHONY : src/random_streams.o

# target to build an object file
src/random_streams.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/random_streams.cpp.o
.PHONY : src/random_streams.cpp.o

src/random_streams.i: src/random_streams.cpp.i

.PHONY : src/random_streams.i

# target to preprocess a source file
src/random_streams.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/random_streams.cpp.i
.PHONY : src/random_streams.cpp.i

src/random_streams.s: src/random_streams.cpp.s

.PHONY : src/random_streams.s

# target to generate assembly for a file
src/random_streams.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/random_streams.cpp.s
.PHONY : src/random_streams.cpp.s

src/solver/aems.o: src/solver/aems.cpp.o

.PHONY : src/solver/aems.o

# target to build an object file
src/solver/aems.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/aems.cpp.o
.PHONY : src/solver/aems.cpp.o

src/solver/aems.i: src/solver/aems.cpp.i

.PHONY : src/solver/aems.i

# target to preprocess a source file
src/solver/aems.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/aems.cpp.i
.PHONY : src/solver/aems.cpp.i

src/solver/aems.s: src/solver/aems.cpp.s

.PHONY : src/solver/aems.s

# target to generate assembly for a file
src/solver/aems.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/aems.cpp.s
.PHONY : src/solver/aems.cpp.s

src/solver/baseline_solver.o: src/solver/baseline_solver.cpp.o

.PHONY : src/solver/baseline_solver.o

# target to build an object file
src/solver/baseline_solver.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/baseline_solver.cpp.o
.PHONY : src/solver/baseline_solver.cpp.o

src/solver/baseline_solver.i: src/solver/baseline_solver.cpp.i

.PHONY : src/solver/baseline_solver.i

# target to preprocess a source file
src/solver/baseline_solver.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/baseline_solver.cpp.i
.PHONY : src/solver/baseline_solver.cpp.i

src/solver/baseline_solver.s: src/solver/baseline_solver.cpp.s

.PHONY : src/solver/baseline_solver.s

# target to generate assembly for a file
src/solver/baseline_solver.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/baseline_solver.cpp.s
.PHONY : src/solver/baseline_solver.cpp.s

src/solver/despot.o: src/solver/despot.cpp.o

.PHONY : src/solver/despot.o

# target to build an object file
src/solver/despot.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/despot.cpp.o
.PHONY : src/solver/despot.cpp.o

src/solver/despot.i: src/solver/despot.cpp.i

.PHONY : src/solver/despot.i

# target to preprocess a source file
src/solver/despot.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/despot.cpp.i
.PHONY : src/solver/despot.cpp.i

src/solver/despot.s: src/solver/despot.cpp.s

.PHONY : src/solver/despot.s

# target to generate assembly for a file
src/solver/despot.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/despot.cpp.s
.PHONY : src/solver/despot.cpp.s

src/solver/pomcp.o: src/solver/pomcp.cpp.o

.PHONY : src/solver/pomcp.o

# target to build an object file
src/solver/pomcp.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/pomcp.cpp.o
.PHONY : src/solver/pomcp.cpp.o

src/solver/pomcp.i: src/solver/pomcp.cpp.i

.PHONY : src/solver/pomcp.i

# target to preprocess a source file
src/solver/pomcp.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/pomcp.cpp.i
.PHONY : src/solver/pomcp.cpp.i

src/solver/pomcp.s: src/solver/pomcp.cpp.s

.PHONY : src/solver/pomcp.s

# target to generate assembly for a file
src/solver/pomcp.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/solver/pomcp.cpp.s
.PHONY : src/solver/pomcp.cpp.s

src/util/coord.o: src/util/coord.cpp.o

.PHONY : src/util/coord.o

# target to build an object file
src/util/coord.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/coord.cpp.o
.PHONY : src/util/coord.cpp.o

src/util/coord.i: src/util/coord.cpp.i

.PHONY : src/util/coord.i

# target to preprocess a source file
src/util/coord.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/coord.cpp.i
.PHONY : src/util/coord.cpp.i

src/util/coord.s: src/util/coord.cpp.s

.PHONY : src/util/coord.s

# target to generate assembly for a file
src/util/coord.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/coord.cpp.s
.PHONY : src/util/coord.cpp.s

src/util/dirichlet.o: src/util/dirichlet.cpp.o

.PHONY : src/util/dirichlet.o

# target to build an object file
src/util/dirichlet.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/dirichlet.cpp.o
.PHONY : src/util/dirichlet.cpp.o

src/util/dirichlet.i: src/util/dirichlet.cpp.i

.PHONY : src/util/dirichlet.i

# target to preprocess a source file
src/util/dirichlet.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/dirichlet.cpp.i
.PHONY : src/util/dirichlet.cpp.i

src/util/dirichlet.s: src/util/dirichlet.cpp.s

.PHONY : src/util/dirichlet.s

# target to generate assembly for a file
src/util/dirichlet.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/dirichlet.cpp.s
.PHONY : src/util/dirichlet.cpp.s

src/util/exec_tracker.o: src/util/exec_tracker.cpp.o

.PHONY : src/util/exec_tracker.o

# target to build an object file
src/util/exec_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/exec_tracker.cpp.o
.PHONY : src/util/exec_tracker.cpp.o

src/util/exec_tracker.i: src/util/exec_tracker.cpp.i

.PHONY : src/util/exec_tracker.i

# target to preprocess a source file
src/util/exec_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/exec_tracker.cpp.i
.PHONY : src/util/exec_tracker.cpp.i

src/util/exec_tracker.s: src/util/exec_tracker.cpp.s

.PHONY : src/util/exec_tracker.s

# target to generate assembly for a file
src/util/exec_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/exec_tracker.cpp.s
.PHONY : src/util/exec_tracker.cpp.s

src/util/floor.o: src/util/floor.cpp.o

.PHONY : src/util/floor.o

# target to build an object file
src/util/floor.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/floor.cpp.o
.PHONY : src/util/floor.cpp.o

src/util/floor.i: src/util/floor.cpp.i

.PHONY : src/util/floor.i

# target to preprocess a source file
src/util/floor.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/floor.cpp.i
.PHONY : src/util/floor.cpp.i

src/util/floor.s: src/util/floor.cpp.s

.PHONY : src/util/floor.s

# target to generate assembly for a file
src/util/floor.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/floor.cpp.s
.PHONY : src/util/floor.cpp.s

src/util/gamma.o: src/util/gamma.cpp.o

.PHONY : src/util/gamma.o

# target to build an object file
src/util/gamma.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/gamma.cpp.o
.PHONY : src/util/gamma.cpp.o

src/util/gamma.i: src/util/gamma.cpp.i

.PHONY : src/util/gamma.i

# target to preprocess a source file
src/util/gamma.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/gamma.cpp.i
.PHONY : src/util/gamma.cpp.i

src/util/gamma.s: src/util/gamma.cpp.s

.PHONY : src/util/gamma.s

# target to generate assembly for a file
src/util/gamma.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/gamma.cpp.s
.PHONY : src/util/gamma.cpp.s

src/util/logging.o: src/util/logging.cpp.o

.PHONY : src/util/logging.o

# target to build an object file
src/util/logging.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/logging.cpp.o
.PHONY : src/util/logging.cpp.o

src/util/logging.i: src/util/logging.cpp.i

.PHONY : src/util/logging.i

# target to preprocess a source file
src/util/logging.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/logging.cpp.i
.PHONY : src/util/logging.cpp.i

src/util/logging.s: src/util/logging.cpp.s

.PHONY : src/util/logging.s

# target to generate assembly for a file
src/util/logging.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/logging.cpp.s
.PHONY : src/util/logging.cpp.s

src/util/random.o: src/util/random.cpp.o

.PHONY : src/util/random.o

# target to build an object file
src/util/random.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/random.cpp.o
.PHONY : src/util/random.cpp.o

src/util/random.i: src/util/random.cpp.i

.PHONY : src/util/random.i

# target to preprocess a source file
src/util/random.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/random.cpp.i
.PHONY : src/util/random.cpp.i

src/util/random.s: src/util/random.cpp.s

.PHONY : src/util/random.s

# target to generate assembly for a file
src/util/random.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/random.cpp.s
.PHONY : src/util/random.cpp.s

src/util/seeds.o: src/util/seeds.cpp.o

.PHONY : src/util/seeds.o

# target to build an object file
src/util/seeds.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/seeds.cpp.o
.PHONY : src/util/seeds.cpp.o

src/util/seeds.i: src/util/seeds.cpp.i

.PHONY : src/util/seeds.i

# target to preprocess a source file
src/util/seeds.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/seeds.cpp.i
.PHONY : src/util/seeds.cpp.i

src/util/seeds.s: src/util/seeds.cpp.s

.PHONY : src/util/seeds.s

# target to generate assembly for a file
src/util/seeds.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/seeds.cpp.s
.PHONY : src/util/seeds.cpp.s

src/util/tinyxml/tinystr.o: src/util/tinyxml/tinystr.cpp.o

.PHONY : src/util/tinyxml/tinystr.o

# target to build an object file
src/util/tinyxml/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinystr.cpp.o
.PHONY : src/util/tinyxml/tinystr.cpp.o

src/util/tinyxml/tinystr.i: src/util/tinyxml/tinystr.cpp.i

.PHONY : src/util/tinyxml/tinystr.i

# target to preprocess a source file
src/util/tinyxml/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinystr.cpp.i
.PHONY : src/util/tinyxml/tinystr.cpp.i

src/util/tinyxml/tinystr.s: src/util/tinyxml/tinystr.cpp.s

.PHONY : src/util/tinyxml/tinystr.s

# target to generate assembly for a file
src/util/tinyxml/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinystr.cpp.s
.PHONY : src/util/tinyxml/tinystr.cpp.s

src/util/tinyxml/tinyxml.o: src/util/tinyxml/tinyxml.cpp.o

.PHONY : src/util/tinyxml/tinyxml.o

# target to build an object file
src/util/tinyxml/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxml.cpp.o
.PHONY : src/util/tinyxml/tinyxml.cpp.o

src/util/tinyxml/tinyxml.i: src/util/tinyxml/tinyxml.cpp.i

.PHONY : src/util/tinyxml/tinyxml.i

# target to preprocess a source file
src/util/tinyxml/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxml.cpp.i
.PHONY : src/util/tinyxml/tinyxml.cpp.i

src/util/tinyxml/tinyxml.s: src/util/tinyxml/tinyxml.cpp.s

.PHONY : src/util/tinyxml/tinyxml.s

# target to generate assembly for a file
src/util/tinyxml/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxml.cpp.s
.PHONY : src/util/tinyxml/tinyxml.cpp.s

src/util/tinyxml/tinyxmlerror.o: src/util/tinyxml/tinyxmlerror.cpp.o

.PHONY : src/util/tinyxml/tinyxmlerror.o

# target to build an object file
src/util/tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlerror.cpp.o
.PHONY : src/util/tinyxml/tinyxmlerror.cpp.o

src/util/tinyxml/tinyxmlerror.i: src/util/tinyxml/tinyxmlerror.cpp.i

.PHONY : src/util/tinyxml/tinyxmlerror.i

# target to preprocess a source file
src/util/tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlerror.cpp.i
.PHONY : src/util/tinyxml/tinyxmlerror.cpp.i

src/util/tinyxml/tinyxmlerror.s: src/util/tinyxml/tinyxmlerror.cpp.s

.PHONY : src/util/tinyxml/tinyxmlerror.s

# target to generate assembly for a file
src/util/tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlerror.cpp.s
.PHONY : src/util/tinyxml/tinyxmlerror.cpp.s

src/util/tinyxml/tinyxmlparser.o: src/util/tinyxml/tinyxmlparser.cpp.o

.PHONY : src/util/tinyxml/tinyxmlparser.o

# target to build an object file
src/util/tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlparser.cpp.o
.PHONY : src/util/tinyxml/tinyxmlparser.cpp.o

src/util/tinyxml/tinyxmlparser.i: src/util/tinyxml/tinyxmlparser.cpp.i

.PHONY : src/util/tinyxml/tinyxmlparser.i

# target to preprocess a source file
src/util/tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlparser.cpp.i
.PHONY : src/util/tinyxml/tinyxmlparser.cpp.i

src/util/tinyxml/tinyxmlparser.s: src/util/tinyxml/tinyxmlparser.cpp.s

.PHONY : src/util/tinyxml/tinyxmlparser.s

# target to generate assembly for a file
src/util/tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/tinyxml/tinyxmlparser.cpp.s
.PHONY : src/util/tinyxml/tinyxmlparser.cpp.s

src/util/util.o: src/util/util.cpp.o

.PHONY : src/util/util.o

# target to build an object file
src/util/util.cpp.o:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/util.cpp.o
.PHONY : src/util/util.cpp.o

src/util/util.i: src/util/util.cpp.i

.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.cpp.i:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/util.cpp.i
.PHONY : src/util/util.cpp.i

src/util/util.s: src/util/util.cpp.s

.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.cpp.s:
	$(MAKE) -f CMakeFiles/despot.dir/build.make CMakeFiles/despot.dir/src/util/util.cpp.s
.PHONY : src/util/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... despot"
	@echo "... despot_adventurer"
	@echo "... despot_bridge"
	@echo "... despot_chain"
	@echo "... despot_navigation"
	@echo "... despot_pocman"
	@echo "... despot_reg_demo"
	@echo "... despot_fvrs"
	@echo "... despot_rock_sample"
	@echo "... despot_simple_rock_sample"
	@echo "... despot_tag"
	@echo "... despot_noisy_laser_tag"
	@echo "... despot_laser_tag"
	@echo "... despot_tiger"
	@echo "... despot_pomdpx"
	@echo "... src/core/builtin_lower_bounds.o"
	@echo "... src/core/builtin_lower_bounds.i"
	@echo "... src/core/builtin_lower_bounds.s"
	@echo "... src/core/builtin_policy.o"
	@echo "... src/core/builtin_policy.i"
	@echo "... src/core/builtin_policy.s"
	@echo "... src/core/builtin_upper_bounds.o"
	@echo "... src/core/builtin_upper_bounds.i"
	@echo "... src/core/builtin_upper_bounds.s"
	@echo "... src/core/globals.o"
	@echo "... src/core/globals.i"
	@echo "... src/core/globals.s"
	@echo "... src/core/mdp.o"
	@echo "... src/core/mdp.i"
	@echo "... src/core/mdp.s"
	@echo "... src/core/node.o"
	@echo "... src/core/node.i"
	@echo "... src/core/node.s"
	@echo "... src/core/particle_belief.o"
	@echo "... src/core/particle_belief.i"
	@echo "... src/core/particle_belief.s"
	@echo "... src/core/pomdp_world.o"
	@echo "... src/core/pomdp_world.i"
	@echo "... src/core/pomdp_world.s"
	@echo "... src/core/solver.o"
	@echo "... src/core/solver.i"
	@echo "... src/core/solver.s"
	@echo "... src/evaluator.o"
	@echo "... src/evaluator.i"
	@echo "... src/evaluator.s"
	@echo "... src/interface/belief.o"
	@echo "... src/interface/belief.i"
	@echo "... src/interface/belief.s"
	@echo "... src/interface/default_policy.o"
	@echo "... src/interface/default_policy.i"
	@echo "... src/interface/default_policy.s"
	@echo "... src/interface/lower_bound.o"
	@echo "... src/interface/lower_bound.i"
	@echo "... src/interface/lower_bound.s"
	@echo "... src/interface/pomdp.o"
	@echo "... src/interface/pomdp.i"
	@echo "... src/interface/pomdp.s"
	@echo "... src/interface/upper_bound.o"
	@echo "... src/interface/upper_bound.i"
	@echo "... src/interface/upper_bound.s"
	@echo "... src/interface/world.o"
	@echo "... src/interface/world.i"
	@echo "... src/interface/world.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/planner.o"
	@echo "... src/planner.i"
	@echo "... src/planner.s"
	@echo "... src/plannerbase.o"
	@echo "... src/plannerbase.i"
	@echo "... src/plannerbase.s"
	@echo "... src/pomdpx/parser/function.o"
	@echo "... src/pomdpx/parser/function.i"
	@echo "... src/pomdpx/parser/function.s"
	@echo "... src/pomdpx/parser/parser.o"
	@echo "... src/pomdpx/parser/parser.i"
	@echo "... src/pomdpx/parser/parser.s"
	@echo "... src/pomdpx/parser/variable.o"
	@echo "... src/pomdpx/parser/variable.i"
	@echo "... src/pomdpx/parser/variable.s"
	@echo "... src/pomdpx/pomdpx.o"
	@echo "... src/pomdpx/pomdpx.i"
	@echo "... src/pomdpx/pomdpx.s"
	@echo "... src/random_streams.o"
	@echo "... src/random_streams.i"
	@echo "... src/random_streams.s"
	@echo "... src/solver/aems.o"
	@echo "... src/solver/aems.i"
	@echo "... src/solver/aems.s"
	@echo "... src/solver/baseline_solver.o"
	@echo "... src/solver/baseline_solver.i"
	@echo "... src/solver/baseline_solver.s"
	@echo "... src/solver/despot.o"
	@echo "... src/solver/despot.i"
	@echo "... src/solver/despot.s"
	@echo "... src/solver/pomcp.o"
	@echo "... src/solver/pomcp.i"
	@echo "... src/solver/pomcp.s"
	@echo "... src/util/coord.o"
	@echo "... src/util/coord.i"
	@echo "... src/util/coord.s"
	@echo "... src/util/dirichlet.o"
	@echo "... src/util/dirichlet.i"
	@echo "... src/util/dirichlet.s"
	@echo "... src/util/exec_tracker.o"
	@echo "... src/util/exec_tracker.i"
	@echo "... src/util/exec_tracker.s"
	@echo "... src/util/floor.o"
	@echo "... src/util/floor.i"
	@echo "... src/util/floor.s"
	@echo "... src/util/gamma.o"
	@echo "... src/util/gamma.i"
	@echo "... src/util/gamma.s"
	@echo "... src/util/logging.o"
	@echo "... src/util/logging.i"
	@echo "... src/util/logging.s"
	@echo "... src/util/random.o"
	@echo "... src/util/random.i"
	@echo "... src/util/random.s"
	@echo "... src/util/seeds.o"
	@echo "... src/util/seeds.i"
	@echo "... src/util/seeds.s"
	@echo "... src/util/tinyxml/tinystr.o"
	@echo "... src/util/tinyxml/tinystr.i"
	@echo "... src/util/tinyxml/tinystr.s"
	@echo "... src/util/tinyxml/tinyxml.o"
	@echo "... src/util/tinyxml/tinyxml.i"
	@echo "... src/util/tinyxml/tinyxml.s"
	@echo "... src/util/tinyxml/tinyxmlerror.o"
	@echo "... src/util/tinyxml/tinyxmlerror.i"
	@echo "... src/util/tinyxml/tinyxmlerror.s"
	@echo "... src/util/tinyxml/tinyxmlparser.o"
	@echo "... src/util/tinyxml/tinyxmlparser.i"
	@echo "... src/util/tinyxml/tinyxmlparser.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

